### ISSUE TITLE
Remove preview

### ISSUE THREAD

**Issue by lucasfrey** [heyday/silverstripe-slices#10]
This is not really an issue but more a simple request.

Is there an easy way to remove the preview functionality on that module? having some trouble with it and I'll like to replace it by the `Slice type` or` Slice Title` for example

Cheers

**Comment by stecman** [comment]
You can completely remove the Slice preview from a GridField using something like:

```php
public function getCMSFields()
{
    $fields = parent::getCMSFields();

    $sliceGridField = $fields->dataFieldByName('Slices');
    $sliceGridField->getConfig()->removeComponentsByType("GridFieldDataObjectPreview");

    return $fields;
}
```

Alternatively, for a few sites I've added some CSS to the CMS to limit the height of the previews:

```css
.ss-gridfield-item .dataobjectpreview {
       position: relative;
       max-height: 200px;
       overflow: hidden;
}
```
Which looks like this (with a slight gradient overlay added):

![image](https://user-images.githubusercontent.com/2230769/39729673-43962266-52b1-11e8-8cd4-47417cf68bce.png)


The user-friendly template name for a slice can be added with:

```php
class ContentSlice extends Slice
{
    private static $summary_fields = [
        'TemplateName' => 'Template'
    ];

    public function getTemplateName()
    {
        $config = $this->getCurrentTemplateConfig();

        if (isset($config['name'])) {
            return $config['name'];
        } else {
            return $this->convertCamelCaseToWords($this->Template);
        }
    }

    // ...
}
```

**Comment by lucasfrey** [comment]
Saving my day @stecman ☄
