### ISSUE TITLE
3rd party git issues

### ISSUE THREAD

**Issue by nimeso** [heyday/silverstripe-slices#8]
When I run 
$ composer require heyday/silverstripe-slices
in windows power shell I'm getting a HEAP of strange errors and permission issues. It keeps asking me for my git user name and password. I'm to scared to continue with the process. I'll try and post you the errors.
![image](https://user-images.githubusercontent.com/1796069/35489149-c5242ed4-04f7-11e8-9228-f61ff4e5c4f4.png)

**Comment by stecman** [comment]
Hey Jamie, you'll want to install `heyday/silverstripe-slices:1.0.0-alpha.4`. The version it's defaulting to (`0.2.1`) requires `simonwelsh/gridfieldrelationhandler` which was taken offline / made private a few years ago.

Despite having "alpha" in the name, `1.0.0-alpha.4` is stable and is used on quite a few sites. The alpha-ness of it is on the CMS UI side, but it's probably time to release this as 1.0 and make any further changes in a future release.
