### ISSUE TITLE
Class 'ContentSlice.Parent' not found

### ISSUE THREAD

**Issue by nimeso** [heyday/silverstripe-slices#9]
Thank you for your help with my last issue.

So I've installed 1.0.0.0-alpha.4 and I'm running SS 3.6 and have done a /dev/build?flush=1 and put 
Page:
  extensions:
    - PageSlicesExtension
but I'm getting this error when I try to edit a page in the CMS.

Uncaught Exception: Class 'ContentSlice.Parent' not found, but used in has_many component 'Slices' on class 'Page'

Cheers heaps

**Comment by stecman** [comment]
That extension [expects you to have a subclass of `Slice` called `ContentSlice`](https://github.com/heyday/silverstripe-slices#subclassing-slice). Have you set that up? Sorry, it's not particularly clear in the readme.

**Comment by nimeso** [comment]
Sweet
